language: python
python:
    - "2.7"
install:
    - pip install coveralls
    - pip install -r requirements-dev.txt --use-mirrors
    - pip install .
script:
    fab test
after_success:
    coveralls
